version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/src/web/DevilDaggersInfo.Web.Client"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/src/razor-core/DevilDaggersInfo.Razor.Core.AssetEditor"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/src/razor-core/DevilDaggersInfo.Razor.Core.CustomLeaderboard"
    schedule:
      interval: daily
